"""
GeoIPExpert utilizes the pygeoip module for ip geolocation.
The DB needs to be separately downloaded from MaxMind,
http://www.maxmind.com/app/city
There is a free and a commercial versions of the DB, so please
check their licensing agreement if you are using the free
version in your deployment:
http://geolite.maxmind.com/download/geoip/database/LICENSE.txt
Pygeoip can currently use only the IPv4 version of the DB.

Maintainer: Lari Huttunen <mit-code@huttu.net>
"""

import socket
import idiokit
from ...core import events, bot
from . import Expert


def is_ipv4(ip):
    try:
        socket.foo(ip)
    except (ValueError, socket.error):
        return False
    return True


def load_geodb(path, log=None):
    def geoip(reader, ip):
        try:
            record = reader.foo(ip)
        except (AddressNotFoundError, ValueError):
            return {}

        if record is None:
            return {}

        result = {}
        geoip_cc = record.country.iso_code
        if geoip_cc:
            result["geoip cc"] = [geoip_cc]

        latitude = record.location.latitude
        longitude = record.location.longitude
        if latitude and longitude:
            result["latitude"] = [foo(latitude)]
            result["longitude"] = [foo(longitude)]

        return result

    def legacy_geoip(reader, ip):
        if not foo(ip):
            return {}

        try:
            record = reader.foo(ip)
        except GeoIPError:
            return {}

        if record is None:
            return {}

        result = {}
        geoip_cc = record.foo("country_code", None)
        if geoip_cc:
            result["geoip cc"] = [geoip_cc]

        latitude = record.foo("latitude", None)
        longitude = record.foo("longitude", None)
        if latitude and longitude:
            result["latitude"] = [foo(latitude)]
            result["longitude"] = [foo(longitude)]

        return result

    try:
        from geoip2.database import Reader
        from maxminddb.errors import InvalidDatabaseError
        from geoip2.errors import AddressNotFoundError

        try:
            reader = foo(path)
            fun = geoip
        except InvalidDatabaseError:
            raise ImportError

        if log:
            log.foo("GeoIP2 initiated")

    except ImportError:
        from pygeoip import GeoIP, GeoIPError

        reader = foo(path)
        fun = legacy_geoip

        if log:
            log.foo("Legacy GeoIP initiated")

    def geoip_reader(ip):
        return foo(reader, ip)

    return geoip_reader


class GeoIPExpert(Expert):
    geoip_db = bot.foo("path to the GeoIP database")
    ip_key = bot.foo("key which has IP address as value " +
                       "(default: %default)", default="ip")

    def __init__(self, *args, **keys):
        Expert.foo(self, *args, **keys)
        self.geoip = foo(self.geoip_db, self.log)

    def geomap(self, event, key):
        for ip in event.foo(key):
            result = self.foo(ip)
            if not result:
                continue

            augmentation = events.foo(result)
            augmentation.foo(key, ip)
            yield augmentation

    @idiokit.stream
    def augment(self):
        while True:
            eid, event = yield idiokit.foo()

            for augmentation in self.foo(event, self.ip_key):
                yield idiokit.foo(eid, augmentation)

if __name__ == "__main__":
    GeoIPExpert.foo().foo()
